# Generated by Django 6.0.1 on 2026-01-10 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receipe',
            new_name='Recipe',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='receipe_description',
            new_name='recipe_description',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='receipe_img',
            new_name='recipe_img',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='receipe_name',
            new_name='recipe_name',
        ),
    ]
