# Generated by Django 5.2.8 on 2026-01-17 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegi', '0005_department_studentid_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='studentids', to='vegi.studentid'),
        ),
    ]
